In [1]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
X = [['Male', 1], ['Female', 3], ['Female', 2]]


In [2]:
X

[['Male', 1], ['Female', 3], ['Female', 2]]

In [3]:
enc.fit(X)

OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='ignore',
       n_values=None, sparse=True)

In [4]:
print(enc.categories_)

[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]


In [5]:
enc.transform([['Female', 1], ['Male', 4]]).toarray()

array([[1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [19]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder


In [9]:
# define example
import pandas as pd
data = pd.DataFrame({"A":[34,12,78,84,26], "B":[1,2,3,1,2]})



In [24]:
data["B"] = data["B"].astype('category')
data = data.values

In [48]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
X = [['Male', 1], ['Female', 3], ['Female', 2]]
XT = enc.fit(X)


In [52]:
X

[['Male', 1], ['Female', 3], ['Female', 2]]

In [53]:
enc.transform(X).toarray()

array([[0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.]])

In [31]:
from sklearn.preprocessing import OneHotEncoder

In [32]:
enc = OneHotEncoder(handle_unknown='ignore')

In [34]:
datax = enc.fit(data)

In [36]:
print(datax)

OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='ignore',
       n_values=None, sparse=True)


In [40]:
X = [['Male', 1], ['Female', 3], ['Female', 2]]

AttributeError: 'list' object has no attribute 'dtypes'

In [42]:
data

array([[34, 1],
       [12, 2],
       [78, 3],
       [84, 1],
       [26, 2]], dtype=object)

In [22]:
value_s = values.astype('category')

TypeError: data type "category" not understood

In [30]:
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(data), 1)



NameError: name 'integer_encoded' is not defined

In [21]:
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


/home/elvi/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [12]:
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['cold']


In [23]:
#NN part

In [62]:

import tensorflow as tf
import tf.keras.models.Sequential
#from keras.models import Sequential
#from keras.layers import Dense, Dropout


ModuleNotFoundError: No module named 'tf'

In [44]:
# Generate dummy data
x_train = np.random.random((1000, 20))
y_train = np.random.randint(2, size=(1000, 1))
x_test = np.random.random((100, 20))
y_test = np.random.randint(2, size=(100, 1))


In [45]:
print(x_train.shape)

(1000, 20)


In [80]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(20, activation='relu'),
  tf.keras.layers.Dense(12, activation='relu'),
  tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(10, activation='softmax')
])


In [83]:
model.compile(optimizer= 'rmsprop', # 'adam',
              loss= 'binary_crossentropy',#'sparse_categorical_crossentropy',
              metrics=['accuracy'])


In [82]:
model.fit(x_train, y_train, epochs=5, batch_size=10)

#model.evaluate(x_test,  y_test, verbose=2)

Epoch 1/5
1000/1000 [==============================] - 1s 981us/sample - loss: 1.2222 - acc: 0.4980
Epoch 2/5
1000/1000 [==============================] - 0s 285us/sample - loss: 1.2085 - acc: 0.4980
Epoch 3/5
1000/1000 [==============================] - 0s 304us/sample - loss: 1.2084 - acc: 0.4980
Epoch 4/5
1000/1000 [==============================] - 0s 272us/sample - loss: 1.2084 - acc: 0.4980
Epoch 5/5
1000/1000 [==============================] - 0s 284us/sample - loss: 1.2084 - acc: 0.4980
